### Valid Create request
POST http://localhost:9000/api/create
Content-Type: application/json

{
  "thought": "Hello, Cousin, v{{$randomInt}}",
  "passphrase": "1121",
  "lifetime": "2006-01-02T15:04:05Z"
}

> {%
  client.global.set("metadataKey", response.body.metadataKey)
  client.global.set("thoughtKey", response.body.thoughtKey)
 %}

### Invalid Create request
POST http://localhost:9000/api/create
Content-Type: application/json

{
  "thought": "Hey",
  "passphrase": "",
  "lifetime": "2006-01-02T15:04:05Z"
}

### GET Metadata request
GET http://localhost:9000/api/metadata/{{metadataKey}}

### Invalid GET Metadata request
GET http://localhost:9000/api/metadata/fda

### GET CheckThoughtExists request
GET http://localhost:9000/api/thought/{{thoughtKey}}

### Invalid GET CheckThoughtExists request
GET http://localhost:9000/api/thought/fda


### Access thought request
POST http://localhost:9000/api/thought/{{thoughtKey}}
Content-Type: application/json

{
  "passphrase": "1121"
}

### Invalid Access thought request with incorrent password
POST http://localhost:9000/api/thought/{{thoughtKey}}
Content-Type: application/json

{
  "passphrase": "lo"
}

### Invalid Access thought request with incorrent thoughtKey
POST http://localhost:9000/api/thought/7c6e0835
Content-Type: application/json

{
  "passphrase": "hello"
}

### Burn thought request
POST http://localhost:9000/api/thought/{{metadataKey}}/burn
Content-Type: application/json

{
  "passphrase": "1121"
}
