### Create user
POST http://localhost:9000/auth/signUp
Content-Type: application/json

{
  "name": "Master Flamaster",
  "username": "name",
  "password": "1111"
}

### Login with user
POST http://localhost:9000/auth/signIn
Content-Type: application/json

{
  "username": "name",
  "password": "1111"
}

> {%
 client.global.set("token", response.body.token)
%}


